### ISSUE TITLE
SemVer parsing

### ISSUE THREAD

**Issue by antonkomarev** [PHLAK/SemVer#11]
```php
$version = new \PHLAK\SemVer\Version('1.0');
```
This code throws an error:
> Invalid Semantic Version string provided

I know that it's not valid for SemVer, but there are a lot of repositories which using SemVer, but their versions are not always has patch number.

**Comment by antonkomarev** [comment]
I think that constructor should accept only versions of 100% correct format, but there could be extra method which will try to make a guess.

```php
$version = \PHLAK\SemVer\Version::parse('1.0');
```

**Comment by PHLAK** [comment]
I'm not sure how I feel about this.

  - If the class is initialized with a version of `1.0` would the library handle it as `1.0` or `1.0.0`?
  - If the minor version is incremented would the version now be `1.1` or `1.1.0`?
  - If the major version is incremented would the version new version be `2.0` or `2.0.0`?

**Comment by antonkomarev** [comment]
I think if it's SemVer - it should have 3 digits delimited with points. If `1.0` passed - it should be instantiated as `1.0.0`, and then minor version increment will be `1.1.0` and major version increment will be `2.0.0`.

**Comment by pokono** [comment]
Maybe there should be an option to make the patch number optional. It's common to hide the patch number if it's zero.

**Comment by PHLAK** [comment]
Added in [v3.2.0](https://github.com/PHLAK/SemVer/releases/tag/3.2.0)
