### ISSUE TITLE
It can check the pre-release tag

### ISSUE THREAD

**Issue by peter279k** [PHLAK/SemVer#2]
According to the `TODO` comment in `gt` and `lt` method inside `Version` class, I think we need to add the feature of `pre-release` tag check.

For example, we have to check the `1.0.0-alpha`, `1.0.0-beta` and `1.0.0-rc` versions comparison.

@PHLAK, do you have any approaches/suggestions about implementing this feature?

Thanks.

**Comment by peter279k** [comment]
Hi @wa7eedem, thank you for your reply.

You can refer this [tutorial](https://getcomposer.org/doc/articles/versions.md) firstly.

I also wait for the repo owner, @PHLAK reply :).

**Comment by PHLAK** [comment]
This is definitely something I'd like to implement but, as with many things in life, there's a bit of thought that needs to go into implementing this and time has not permitted. I will keep the issue open though to track this.

**Comment by PHLAK** [comment]
This is now implemented with the 3.0.0 release.
