### ISSUE TITLE
Add Version::isPre(), Version::hasBuild()

### ISSUE THREAD

**Issue by raubv0gel** [PHLAK/SemVer#25]
Thanks for developing this lib!

It would be useful, if we implement functions like Version::isPre() and Version::hasBuild() to check if a version is a pre version or/and a version has a build part.

**Comment by PHLAK** [comment]
This is a good idea. Thanks.

**Comment by PHLAK** [comment]
A PR would be welcome, thanks!

**Comment by raubv0gel** [comment]
PR #28 added.

**Comment by PHLAK** [comment]
Implemented in a16851cc529ba30a2ba3a9eb785fa0249afd2c89
